### ISSUE TITLE
Postman collection

### ISSUE THREAD

**Issue by ilusi0n** [ilusi0n/RotaDasTapas#14]
Create a postman collection for the service for the two existing endpoints.

**Comment by praktikon** [comment]
Hello! I've made the collection file but i have no idea where to put it.

**Comment by ilusi0n** [comment]
Hello!

Thank you! Probably inside the RotaDasTapas folder, create a folder called "PostmanCollection". What do you think?

Thank you once more!

**Comment by praktikon** [comment]
I'm for it!
